# Charitable Donation Analysis Configuration

# Hydra configuration
defaults:
  - _self_
  - override hydra/hydra_logging: disabled
  - override hydra/job_logging: disabled

hydra:
  output_subdir: null
  run:
    dir: .

# Input data file path
input_file: "../data.csv"

# Output format settings
generate_html: true       # Generate html
generate_markdown: true   # Generate markdown analysis report
generate_textfile: true   # A simple text file

# Report sections in order with  optional configuration
# Available sections:
# - exec: Executive Summary
# - sectors: Donation Analysis by Charitable Sector
# - yearly: Yearly Donation Analysis
# - top_charities: Top N Charities by Total Donations
# - focus_summary: Focus Charities Summary (EIN, name, total donated, last donation date)
# - patterns: One-Time vs Recurring Donation Patterns
# - detailed: Detailed Analysis of Top N Charities

sections:
  - name: exec
    # Executive Summary - no options yet

  - name: sectors
    # Donation Analysis by Charitable Sector
    # options:
    #   show_percentages: true

  - name: yearly
    # Yearly Donation Analysis
    # options:
    #   include_charts: true

  - name: top_charities
    # Top 10 Charities by Total Donations
    options:
      count: 15

  - name: focus_summary
    # Focus Charities Summary - simple list with last donation and total

  - name: patterns
    # One-Time vs Recurring Donation Patterns
    # options:
    #   max_one_time_shown: 20

  - name: detailed
    # Detailed Analysis of Top 10 Charities
    # options:
    #   include_descriptions: true

# Output directory
output_dir: "../output"

# Charity Navigator API settings (optional)
charity_navigator:
  app_id: "3069"
  app_key: null  # Set environment variable CHARITY_NAVIGATOR_APP_KEY

# Charapi configuration path (for charity evaluations)
charapi_config_path: "/Users/pitosalas/mydev/charapi/charapi/config/config.yaml"
