mock_mode: false

propublica:
  base_url: "https://projects.propublica.org/nonprofits/api/v2"
  timeout: 30
  mock_mode: false

scoring:
  financial:
    program_expense_target: 0.75
    admin_expense_limit: 0.15
    fundraising_expense_limit: 0.15
    program_score_max: 40
    admin_score_max: 20
    fundraising_score_max: 20
    stability_score_max: 20
  
  trend:
    years_to_analyze: 5
    growth_score_range: 10
    volatility_penalty_range: 10

caching:
  enabled: true
  api_cache_hours: 24